name: Build and Test the Prog8 compiler

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: install 64tass
        run: |
          sudo apt update
          sudo apt install 64tass
          64tass --version

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Compile
        run: ./gradlew compileKotlin compileTestKotlin --console=plain

      - name: Test
        run: ./gradlew test --continue --console=plain

      - name: Package
        run: |
          ./gradlew shadowJar --console=plain
          sha256sum -b compiler/build/libs/*-all.jar > compiler/build/libs/hash.txt

      - name: Create compiler shadowJar artifact
        uses: actions/upload-artifact@v6
        with:
          name: prog8-compiler-jar-zipped
          path: |
            compiler/build/libs/*-all.jar
            compiler/build/libs/hash.txt

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: test-results
          path: compiler/build/test-results/test/

